In [29]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('/home/sarvagya/Downloads/ml-20m/ratings.csv')
X = dataset.iloc[:1000000, :]
# X.loc[X['movieId'] == 1].shape
X

userId  movieId  rating   timestamp
0            1        2     3.5  1112486027
1            1       29     3.5  1112484676
2            1       32     3.5  1112484819
3            1       47     3.5  1112484727
4            1       50     3.5  1112484580
5            1      112     3.5  1094785740
6            1      151     4.0  1094785734
7            1      223     4.0  1112485573
8            1      253     4.0  1112484940
9            1      260     4.0  1112484826
10           1      293     4.0  1112484703
11           1      296     4.0  1112484767
12           1      318     4.0  1112484798
13           1      337     3.5  1094785709
14           1      367     3.5  1112485980
15           1      541     4.0  1112484603
16           1      589     3.5  1112485557
17           1      593     3.5  1112484661
18           1      653     3.0  1094785691
19           1      919     3.5  1094785621
20           1      924     3.5  1094785598
21           1     1009     3.5  1112486013
22           1     1036     4.0  1112485480
23           1     1079     4.0  1094785665
24           1     1080     3.5  1112485375
25           1     1089     3.5  1112484669
26           1     1090     4.0  1112485453
27           1     1097     4.0  1112485701
28           1     1136     3.5  1112484609
29           1     1193     3.5  1112484690
...        ...      ...     ...         ...
999970    6743     1288     3.0  1117837782
999971    6743     1302     3.5  1117761279
999972    6743     1320     4.0  1117759851
999973    6743     1339     3.5  1117761492
999974    6743     1350     3.0  1117762158
999975    6743     1377     4.0  1117761306
999976    6743     1387     3.5  1117760925
999977    6743     1391     4.0  1117761055
999978    6743     1393     4.0  1117760877
999979    6743     1405     2.5  1117761516
999980    6743     1407     3.5  1117761086
999981    6743     1409     3.0  1117761862
999982    6743     1466     4.5  1117761456
999983    6743     1479     3.5  1117761577
999984    6743     1485     4.0  1117761156
999985    6743     1500     4.0  1117761150
999986    6743     1513     1.0  1117761571
999987    6743     1517     4.0  1117760999
999988    6743     1527     4.0  1117760899
999989    6743     1544     3.5  1117761201
999990    6743     1552     3.5  1117761293
999991    6743     1556     2.0  1117762246
999992    6743     1562     3.0  1117761635
999993    6743     1566     4.0  1117762257
999994    6743     1573     3.0  1117761043
999995    6743     1580     4.0  1117760757
999996    6743     1584     3.0  1117760943
999997    6743     1586     3.0  1117761831
999998    6743     1589     4.0  1117761990
999999    6743     1590     4.0  1117761913

[1000000 rows x 4 columns]

In [3]:
dataset2 = pd.read_csv('/home/sarvagya/Downloads/ml-20m/movies.csv')
W = dataset2.iloc[:, :]
W

movieId                                              title  \
0            1                                   Toy Story (1995)   
1            2                                     Jumanji (1995)   
2            3                            Grumpier Old Men (1995)   
3            4                           Waiting to Exhale (1995)   
4            5                 Father of the Bride Part II (1995)   
5            6                                        Heat (1995)   
6            7                                     Sabrina (1995)   
7            8                                Tom and Huck (1995)   
8            9                                Sudden Death (1995)   
9           10                                   GoldenEye (1995)   
10          11                     American President, The (1995)   
11          12                 Dracula: Dead and Loving It (1995)   
12          13                                       Balto (1995)   
13          14                                       Nixon (1995)   
14          15                            Cutthroat Island (1995)   
15          16                                      Casino (1995)   
16          17                       Sense and Sensibility (1995)   
17          18                                  Four Rooms (1995)   
18          19              Ace Ventura: When Nature Calls (1995)   
19          20                                 Money Train (1995)   
20          21                                  Get Shorty (1995)   
21          22                                     Copycat (1995)   
22          23                                   Assassins (1995)   
23          24                                      Powder (1995)   
24          25                           Leaving Las Vegas (1995)   
25          26                                     Othello (1995)   
26          27                                Now and Then (1995)   
27          28                                  Persuasion (1995)   
28          29  City of Lost Children, The (Cité des enfants p...   
29          30  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
...        ...                                                ...   
27248   131146                      Werner - Volles Rooäää (1999)   
27249   131148                                  What A Man (2011)   
27250   131150         7 Dwarves: The Forest Is Not Enough (2006)   
27251   131152                                 The Fat Spy (1966)   
27252   131154  Die Bademeister – Weiber, saufen, Leben retten...   
27253   131156                         Ants in the Pants 2 (2002)   
27254   131158                                Manta, Manta (1991)   
27255   131160                  Oscar and the Lady in Pink (2009)   
27256   131162                      Por un puñado de besos (2014)   
27257   131164                               Vietnam in HD (2011)   
27258   131166                                  WWII IN HD (2009)   
27259   131168                                     Phoenix (2014)   
27260   131170                                   Parallels (2015)   
27261   131172                              Closed Curtain (2013)   
27262   131174                                   Gentlemen (2014)   
27263   131176                             A Second Chance (2014)   
27264   131180                     Dead Rising: Watchtower (2015)   
27265   131231                                     Standby (2014)   
27266   131237                         What Men Talk About (2010)   
27267   131239                          Three Quarter Moon (2011)   
27268   131241                           Ants in the Pants (2000)   
27269   131243                Werner - Gekotzt wird später (2003)   
27270   131248                              Brother Bear 2 (2006)   
27271   131250                              No More School (2000)   
27272   131252  Forklift Driver Klaus: The First Day on the Jo...   
27273   131254                       Kein Bund für's Leben (2007)   
27274

In [4]:
sorter = X['movieId'].value_counts().index
sorter

Int64Index([   296,    356,    593,    318,    480,    260,    110,    589,
              2571,    527,
            ...
              3333, 113557,  58136,  91286,  25942,   8828,  95628,  38320,
            117885,   6729],
           dtype='int64', length=13950)

In [5]:
sorterIndex = dict(zip(sorter,range(len(sorter))))

# Generate a rank column that will be used to sort
# the dataframe numerically
W['movieId_Rank'] = W['movieId'].map(sorterIndex)

# Here is the result asked with the lexicographic sort
# Result may be hard to analyze, so a second sorting is
# proposed next
## NOTE: 
## Newer versions of pandas use 'sort_value' instead of 'sort'
W.sort_values(['movieId_Rank'], \
        ascending = [True], inplace = True)
W.drop('movieId_Rank', 1, inplace = True)


In [6]:
W = W.reset_index(drop = True)

In [7]:
W['movieId'] = W.index
W

movieId                                              title  \
0            0                                Pulp Fiction (1994)   
1            1                                Forrest Gump (1994)   
2            2                   Silence of the Lambs, The (1991)   
3            3                   Shawshank Redemption, The (1994)   
4            4                               Jurassic Park (1993)   
5            5          Star Wars: Episode IV - A New Hope (1977)   
6            6                                  Braveheart (1995)   
7            7                  Terminator 2: Judgment Day (1991)   
8            8                                 Matrix, The (1999)   
9            9                            Schindler's List (1993)   
10          10                               Fugitive, The (1993)   
11          11                                   Toy Story (1995)   
12          12               Independence Day (a.k.a. ID4) (1996)   
13          13                                   Apollo 13 (1995)   
14          14                         Usual Suspects, The (1995)   
15          15  Star Wars: Episode VI - Return of the Jedi (1983)   
16          16  Star Wars: Episode V - The Empire Strikes Back...   
17          17                                      Batman (1989)   
18          18                             American Beauty (1999)   
19          19          Twelve Monkeys (a.k.a. 12 Monkeys) (1995)   
20          20  Raiders of the Lost Ark (Indiana Jones and the...   
21          21                          Dances with Wolves (1990)   
22          22                                       Fargo (1996)   
23          23                                   True Lies (1994)   
24          24                        Seven (a.k.a. Se7en) (1995)   
25          25                                       Speed (1994)   
26          26                          Back to the Future (1985)   
27          27                                     Aladdin (1992)   
28          28                              Godfather, The (1972)   
29          29                                  Fight Club (1999)   
...        ...                                                ...   
27248    27248                      Werner - Volles Rooäää (1999)   
27249    27249                                  What A Man (2011)   
27250    27250         7 Dwarves: The Forest Is Not Enough (2006)   
27251    27251                                 The Fat Spy (1966)   
27252    27252  Die Bademeister – Weiber, saufen, Leben retten...   
27253    27253                         Ants in the Pants 2 (2002)   
27254    27254                                Manta, Manta (1991)   
27255    27255                  Oscar and the Lady in Pink (2009)   
27256    27256                      Por un puñado de besos (2014)   
27257    27257                               Vietnam in HD (2011)   
27258    27258                                  WWII IN HD (2009)   
27259    27259                                     Phoenix (2014)   
27260    27260                                   Parallels (2015)   
27261    27261                              Closed Curtain (2013)   
27262    27262                                   Gentlemen (2014)   
27263    27263                             A Second Chance (2014)   
27264    27264                     Dead Rising: Watchtower (2015)   
27265    27265                                     Standby (2014)   
27266    27266                         What Men Talk About (2010)   
27267    27267                          Three Quarter Moon (2011)   
27268    27268                           Ants in the Pants (2000)   
27269    27269                Werner - Gekotzt wird später (2003)   
27270    27270                              Brother Bear 2 (2006)   
27271    27271                              No More School (2000)   
27272    27272  Forklift Driver Klaus: The First Day on the Jo...   
27273    27273                       Kein Bund für's Leben (2007)   
27274

In [30]:
X['freq'] = X.groupby('movieId')['movieId'].transform('count')
X = X.sort_values(['freq' , 'movieId'] , ascending = [False , True])


/home/sarvagya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [31]:
# X['freq'] = X.groupby('movieId')['movieId'].transform('count')
# X = X.sort_values(['freq' , 'movieId'] , ascending = [False , True])
X = X.reset_index(drop = True)
X

userId  movieId  rating   timestamp  freq
0            1      296     4.0  1112484767  3320
1            8      296     5.0   833973081  3320
2           11      296     3.5  1230858799  3320
3           13      296     5.0   849082366  3320
4           15      296     3.0   840206642  3320
5           18      296     4.0  1195573677  3320
6           21      296     5.0   992188845  3320
7           22      296     5.0   994638043  3320
8           23      296     5.0   914457789  3320
9           24      296     5.0   994071115  3320
10          25      296     4.0  1277962554  3320
11          26      296     5.0   839270563  3320
12          28      296     5.0   834092660  3320
13          29      296     5.0   835561519  3320
14          32      296     5.0   845962251  3320
15          34      296     3.0   839249781  3320
16          35      296     5.0  1164499167  3320
17          38      296     1.0   835717875  3320
18          42      296     4.5  1411667904  3320
19          43      296     4.0  1239308843  3320
20          44      296     4.0  1038250811  3320
21          46      296     5.0   846354218  3320
22          47      296     4.0  1239940370  3320
23          48      296     5.0   850710783  3320
24          49      296     5.0  1367549413  3320
25          50      296     5.0  1182348326  3320
26          51      296     5.0   938801847  3320
27          52      296     3.0   836485463  3320
28          53      296     3.0   938941890  3320
29          54      296     5.0   974836695  3320
...        ...      ...     ...         ...   ...
999970    3453   127196     0.5  1426106495     1
999971    3453   127212     0.5  1426106507     1
999972    5192   127222     4.5  1422724164     1
999973    5192   127224     3.5  1422724287     1
999974    2650   127302     3.5  1422799897     1
999975    3358   127319     4.0  1427610501     1
999976    3358   127323     2.5  1423338288     1
999977    5107   127881     3.0  1423368222     1
999978    3029   128510     3.0  1423845599     1
999979    5840   128520     4.0  1424139347     1
999980    3029   128601     2.5  1424009947     1
999981    3029   128622     3.0  1424017779     1
999982    4450   128648     2.0  1427592277     1
999983    1141   128686     3.0  1424079101     1
999984     964   128715     4.0  1424133260     1
999985    6233   128736     1.0  1424644553     1
999986    1239   128832     4.5  1425335168     1
999987    1721   128842     3.0  1425957532     1
999988    3453   129030     1.0  1426106421     1
999989    4450   129233     2.0  1427592123     1
999990    5514   129235     3.5  1424822663     1
999991    3397   129303     2.5  1424928011     1
999992    6233   129350     3.5  1425072280     1
999993    2930   129354     3.5  1427035572     1
999994    3453   129707     0.5  1426106407     1
999995    3858   130052     1.0  1426949476     1
999996    4450   130073     2.5  1427591774     1
999997    1339   130219     4.5  1426852156     1
999998    5731   130462     4.0  1427217650     1
999999    3858   130642     3.0  1427138517     1

[1000000 rows x 5 columns]

In [32]:
j = X.iloc[0,1]
k = 0
# Q = X[0:100].copy()
# Q
for index,row in X.iterrows():
    if(row['movieId'] != j):
        k += 1
        j = row['movieId']
    X.set_value(index , 'movieId' , k)
#     X.loc[index, 'movieId'] = k
    if(k == 500):
        break
# i = 0
# for j in rated_recom:
#     for k in j:
#         recommendations.loc[recommendations['movie'] == k, 'rating'] += ratings[i]
# #         recommendations.set_value(row, 'rating', row['rating'] + ratings[i])
#     i += 1

/home/sarvagya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':


In [33]:
k

500

In [47]:
# for index,row in X.iterrows():
#     for i in range(len(sorter)):
#         if(row['movieId'] == sorter[i]):
#             X[index,'movieId'] = iX.loc[X[]]
X

userId  movieId  rating   timestamp  freq
0            1        0     4.0  1112484767  3320
1            8        0     5.0   833973081  3320
2           11        0     3.5  1230858799  3320
3           13        0     5.0   849082366  3320
4           15        0     3.0   840206642  3320
5           18        0     4.0  1195573677  3320
6           21        0     5.0   992188845  3320
7           22        0     5.0   994638043  3320
8           23        0     5.0   914457789  3320
9           24        0     5.0   994071115  3320
10          25        0     4.0  1277962554  3320
11          26        0     5.0   839270563  3320
12          28        0     5.0   834092660  3320
13          29        0     5.0   835561519  3320
14          32        0     5.0   845962251  3320
15          34        0     3.0   839249781  3320
16          35        0     5.0  1164499167  3320
17          38        0     1.0   835717875  3320
18          42        0     4.5  1411667904  3320
19          43        0     4.0  1239308843  3320
20          44        0     4.0  1038250811  3320
21          46        0     5.0   846354218  3320
22          47        0     4.0  1239940370  3320
23          48        0     5.0   850710783  3320
24          49        0     5.0  1367549413  3320
25          50        0     5.0  1182348326  3320
26          51        0     5.0   938801847  3320
27          52        0     3.0   836485463  3320
28          53        0     3.0   938941890  3320
29          54        0     5.0   974836695  3320
...        ...      ...     ...         ...   ...
999970    3453   127196     0.5  1426106495     1
999971    3453   127212     0.5  1426106507     1
999972    5192   127222     4.5  1422724164     1
999973    5192   127224     3.5  1422724287     1
999974    2650   127302     3.5  1422799897     1
999975    3358   127319     4.0  1427610501     1
999976    3358   127323     2.5  1423338288     1
999977    5107   127881     3.0  1423368222     1
999978    3029   128510     3.0  1423845599     1
999979    5840   128520     4.0  1424139347     1
999980    3029   128601     2.5  1424009947     1
999981    3029   128622     3.0  1424017779     1
999982    4450   128648     2.0  1427592277     1
999983    1141   128686     3.0  1424079101     1
999984     964   128715     4.0  1424133260     1
999985    6233   128736     1.0  1424644553     1
999986    1239   128832     4.5  1425335168     1
999987    1721   128842     3.0  1425957532     1
999988    3453   129030     1.0  1426106421     1
999989    4450   129233     2.0  1427592123     1
999990    5514   129235     3.5  1424822663     1
999991    3397   129303     2.5  1424928011     1
999992    6233   129350     3.5  1425072280     1
999993    2930   129354     3.5  1427035572     1
999994    3453   129707     0.5  1426106407     1
999995    3858   130052     1.0  1426949476     1
999996    4450   130073     2.5  1427591774     1
999997    1339   130219     4.5  1426852156     1
999998    5731   130462     4.0  1427217650     1
999999    3858   130642     3.0  1427138517     1

[1000000 rows x 5 columns]

In [36]:
X

userId  movieId  rating   timestamp  freq
0            1        0     4.0  1112484767  3320
1            8        0     5.0   833973081  3320
2           11        0     3.5  1230858799  3320
3           13        0     5.0   849082366  3320
4           15        0     3.0   840206642  3320
5           18        0     4.0  1195573677  3320
6           21        0     5.0   992188845  3320
7           22        0     5.0   994638043  3320
8           23        0     5.0   914457789  3320
9           24        0     5.0   994071115  3320
10          25        0     4.0  1277962554  3320
11          26        0     5.0   839270563  3320
12          28        0     5.0   834092660  3320
13          29        0     5.0   835561519  3320
14          32        0     5.0   845962251  3320
15          34        0     3.0   839249781  3320
16          35        0     5.0  1164499167  3320
17          38        0     1.0   835717875  3320
18          42        0     4.5  1411667904  3320
19          43        0     4.0  1239308843  3320
20          44        0     4.0  1038250811  3320
21          46        0     5.0   846354218  3320
22          47        0     4.0  1239940370  3320
23          48        0     5.0   850710783  3320
24          49        0     5.0  1367549413  3320
25          50        0     5.0  1182348326  3320
26          51        0     5.0   938801847  3320
27          52        0     3.0   836485463  3320
28          53        0     3.0   938941890  3320
29          54        0     5.0   974836695  3320
...        ...      ...     ...         ...   ...
999970    3453   127196     0.5  1426106495     1
999971    3453   127212     0.5  1426106507     1
999972    5192   127222     4.5  1422724164     1
999973    5192   127224     3.5  1422724287     1
999974    2650   127302     3.5  1422799897     1
999975    3358   127319     4.0  1427610501     1
999976    3358   127323     2.5  1423338288     1
999977    5107   127881     3.0  1423368222     1
999978    3029   128510     3.0  1423845599     1
999979    5840   128520     4.0  1424139347     1
999980    3029   128601     2.5  1424009947     1
999981    3029   128622     3.0  1424017779     1
999982    4450   128648     2.0  1427592277     1
999983    1141   128686     3.0  1424079101     1
999984     964   128715     4.0  1424133260     1
999985    6233   128736     1.0  1424644553     1
999986    1239   128832     4.5  1425335168     1
999987    1721   128842     3.0  1425957532     1
999988    3453   129030     1.0  1426106421     1
999989    4450   129233     2.0  1427592123     1
999990    5514   129235     3.5  1424822663     1
999991    3397   129303     2.5  1424928011     1
999992    6233   129350     3.5  1425072280     1
999993    2930   129354     3.5  1427035572     1
999994    3453   129707     0.5  1426106407     1
999995    3858   130052     1.0  1426949476     1
999996    4450   130073     2.5  1427591774     1
999997    1339   130219     4.5  1426852156     1
999998    5731   130462     4.0  1427217650     1
999999    3858   130642     3.0  1427138517     1

[1000000 rows x 5 columns]

In [48]:
Y = pd.DataFrame()
X = X.loc[X['userId'] <= 1000]
for p in range(500):
    Y = Y.append(X.loc[X['movieId'] == p], ignore_index = True)
Y = Y.iloc[: , :4]
Y = Y.sort_values([ 'movieId' , 'userId'])
Y

userId  movieId  rating   timestamp
0           1        0     4.0  1112484767
1           8        0     5.0   833973081
2          11        0     3.5  1230858799
3          13        0     5.0   849082366
4          15        0     3.0   840206642
5          18        0     4.0  1195573677
6          21        0     5.0   992188845
7          22        0     5.0   994638043
8          23        0     5.0   914457789
9          24        0     5.0   994071115
10         25        0     4.0  1277962554
11         26        0     5.0   839270563
12         28        0     5.0   834092660
13         29        0     5.0   835561519
14         32        0     5.0   845962251
15         34        0     3.0   839249781
16         35        0     5.0  1164499167
17         38        0     1.0   835717875
18         42        0     4.5  1411667904
19         43        0     4.0  1239308843
20         44        0     4.0  1038250811
21         46        0     5.0   846354218
22         47        0     4.0  1239940370
23         48        0     5.0   850710783
24         49        0     5.0  1367549413
25         50        0     5.0  1182348326
26         51        0     5.0   938801847
27         52        0     3.0   836485463
28         53        0     3.0   938941890
29         54        0     5.0   974836695
...       ...      ...     ...         ...
75515     672      499     5.0  1298314700
75516     675      499     4.0   867946638
75517     709      499     3.0   942672190
75518     710      499     5.0   947825616
75519     738      499     4.5  1204097569
75520     739      499     4.0  1214347197
75521     741      499     5.0  1192573233
75522     761      499     3.0   903141568
75523     774      499     4.5  1314135681
75524     775      499     4.5  1113798952
75525     776      499     3.0   962984077
75526     790      499     5.0   940106463
75527     792      499     3.5  1064601073
75528     802      499     5.0  1015508590
75529     810      499     2.0   993238663
75530     811      499     5.0  1341332949
75531     815      499     4.0  1266748045
75532     847      499     4.0  1116286141
75533     853      499     5.0   856443297
75534     868      499     5.0  1122762901
75535     903      499     5.0   902107624
75548     903      499     2.0   903967630
75536     909      499     5.0   939674799
75537     910      499     4.5  1078336345
75538     943      499     5.0   859393305
75539     947      499     4.0   950772967
75540     955      499     3.0   953652342
75541     969      499     3.0  1390180491
75542     971      499     5.0  1201463494
75543     987      499     4.0   943908944

[75549 rows x 4 columns]

In [49]:
A = Y['userId']
B = Y['movieId']
C = Y['rating']

In [50]:
##

In [51]:
##

In [52]:
P = np.zeros((1000,500))
P
np.any(np.isnan(P))

False

In [53]:
for i in range(len(A)):
    if(A[i] < 1000 and B[i] < 500):
        P[A[i] - 1 , B[i]] = C[i]
P
np.any(np.isnan(P))

False

In [54]:
j = 0
k = []
for i in P:
    a = i.sum()
    b = np.count_nonzero(i)
    if(a == 0):
        print(j)
        k.append(j)
    j += 1
    #print(a,b)
#np.any(np.isnan(P))
P = np.delete(P , k , 0)
P.shape

860
865
957
999


(996, 500)

In [55]:
# mean = []
# for i in range(P.shape[0]):
#     a = P[i].sum()
#     b = np.count_nonzero(P[i])
#     mean.append(a/b)
#     #print(a,b)
# for i in range(P.shape[0]):
#     for j in range(P.shape[1]):
#         if(P[i,j] != 0):
#             P[i,j] -= mean[i]
# P
# #np.any(np.isnan(P))

In [56]:
np.isnan(P).sum()

0

In [57]:
np.any(np.isnan(P))

False

In [58]:
P[0,:].mean()

0.694

In [59]:
# from sklearn.metrics.pairwise import linear_kernel
# from sklearn.metrics.pairwise import cosine_similarity

# #cosine_sim = cosine_similarity(P[: , [0,1]] , P[: , [0,1]])
# cosine_sim = cosine_similarity(P , P)
# cosine_sim

In [60]:
# from sklearn.metrics.pairwise import cosine_similarity
# from scipy import sparse

# P_sparse = sparse.csr_matrix(P)
# similarities = cosine_similarity(P_sparse)
# print('pairwise dense output:\n {}\n'.format(similarities))

# #also can output sparse matrices
# #similarities_sparse = cosine_similarity(A_sparse,dense_output=False)
# #print('pairwise sparse output:\n {}\n'.format(similarities_sparse))
# similarities.shape

In [61]:
# dataset2 = pd.read_csv('/home/sarvagya/Downloads/ml-20m/movies.csv')
# W = dataset2.iloc[:, :]
# W

In [170]:
n = int(input())

15


In [171]:
B = np.zeros(500)
for i in range(n):
    x = int(input())
    B[i] = x

4
1
3
5
2
4
1
2
3
5
3
3
4
2
1


In [172]:
P = np.vstack([P, B])

In [173]:
P[len(P) - 1,:]

array([4., 1., 3., 5., 2., 4., 1., 2., 3., 5., 3., 3., 4., 2., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [174]:
from sklearn.metrics.pairwise import linear_kernel
from sklearn.metrics.pairwise import cosine_similarity

#cosine_sim = cosine_similarity(P[: , [0,1]] , P[: , [0,1]])
cosine_sim = cosine_similarity(P , P)
cosine_sim

array([[1.        , 0.1892847 , 0.37717179, ..., 0.07016666, 0.13948093,
        0.16358567],
       [0.1892847 , 1.        , 0.29033475, ..., 0.12970364, 0.19204899,
        0.15071675],
       [0.37717179, 0.29033475, 1.        , ..., 0.11928839, 0.2514695 ,
        0.24662516],
       ...,
       [0.07016666, 0.12970364, 0.11928839, ..., 1.        , 0.17183301,
        0.15638809],
       [0.13948093, 0.19204899, 0.2514695 , ..., 0.17183301, 1.        ,
        0.89287966],
       [0.16358567, 0.15071675, 0.24662516, ..., 0.15638809, 0.89287966,
        1.        ]])

In [175]:
cosine_sim?

In [176]:
cosine_sim[len(cosine_sim) - 1]

array([0.16358567, 0.15071675, 0.24662516, 0.08795735, 0.29029728,
       0.18938138, 0.12868575, 0.31186147, 0.02470077, 0.2053736 ,
       0.26017919, 0.31287456, 0.35286395, 0.1729619 , 0.38566369,
       0.0529858 , 0.11431267, 0.3111793 , 0.11705751, 0.05966274,
       0.24625642, 0.25020007, 0.29396325, 0.24046496, 0.22467466,
       0.39944407, 0.02931118, 0.18446367, 0.23575795, 0.02940871,
       0.14500248, 0.41826058, 0.0085295 , 0.2042068 , 0.24969974,
       0.        , 0.        , 0.20640687, 0.22688641, 0.05640661,
       0.1229916 , 0.18749273, 0.26283643, 0.12079429, 0.04257706,
       0.1882707 , 0.32702605, 0.27017435, 0.28883915, 0.19171956,
       0.16682406, 0.25117175, 0.15028797, 0.26209939, 0.17823701,
       0.20021575, 0.04231906, 0.18340362, 0.20261551, 0.22861687,
       0.111334  , 0.11135968, 0.10820262, 0.32286977, 0.15077923,
       0.14356715, 0.1075814 , 0.08944715, 0.26192901, 0.31879447,
       0.12599427, 0.16040247, 0.26458791, 0.04631382, 0.34262

In [177]:
A = cosine_sim[len(cosine_sim) - 1].argsort()[-16:][::-1]

In [178]:
A

array([997, 996, 970, 220, 683, 354, 773, 318, 110, 992, 559, 588, 858,
       804, 184, 541])

In [179]:
L = np.zeros(500)
for i in range(1,len(A)):
    S = P[A[i]].argsort()[-15:][::-1]
    print(S)
    for j in S:
        L[j] = 1
T = L.argsort()[-15:][::-1]
T
# movie_rat = np.zeros(500)
    

[ 0  5 10  4 12  8 11  1  9 14  3  7 13  6  2]
[  0  22 489  15  14  24   9   8   5   2   6  16   1  17   4]
[  2   5  17   3 212  23  21 260 216   7 381  11   0 310 177]
[  0   9  41  25 233  13  12  70  45   4   3   2 128 166 137]
[ 28   8   3   5  16   9 362 135 170 499 169 168 167 166 165]
[483 441   2   3   5 305   9  55  20 133 499  13 294   1 394]
[  3 381 400   9   1   2   7 132  23  22  12 444   6  21 385]
[482   3 439   9 362  12 159 160 161 158 162 163 171 164 165]
[  0  41   2   3   6   7   9  10  25 477  21  23  24  27  74]
[100   3  68  18   0   8 109 407 105  29   6  10 186   2  62]
[309  11 446   4   7 486 424 285 461 390  15  12   0   5   2]
[  0 106   2   3   6  24  14  13 112  31  58  23  85  82 120]
[  0   2 197  13  11  40  17   3   6 154  10  27  33  51 120]
[309 359   1   2   3 228  23  13   0   4   7 234 348 350 360]
[  0   9   1 470 451  53  74  13 221  10 166 191   3 390 347]


array([499, 400, 177, 171, 170, 169, 168, 167, 166, 165, 164, 163, 162,
       161, 160])

In [180]:
movie_rat = pd.DataFrame(columns=['rating','sim','score'] , index=range(0,500))
movie_rat['rating'] = 0
movie_rat['sim'] = 0
movie_rat['score'] = 0
movie_rat

rating  sim  score
0         0    0      0
1         0    0      0
2         0    0      0
3         0    0      0
4         0    0      0
5         0    0      0
6         0    0      0
7         0    0      0
8         0    0      0
9         0    0      0
10        0    0      0
11        0    0      0
12        0    0      0
13        0    0      0
14        0    0      0
15        0    0      0
16        0    0      0
17        0    0      0
18        0    0      0
19        0    0      0
20        0    0      0
21        0    0      0
22        0    0      0
23        0    0      0
24        0    0      0
25        0    0      0
26        0    0      0
27        0    0      0
28        0    0      0
29        0    0      0
..      ...  ...    ...
470       0    0      0
471       0    0      0
472       0    0      0
473       0    0      0
474       0    0      0
475       0    0      0
476       0    0      0
477       0    0      0
478       0    0      0
479       0    0      0
480       0    0      0
481       0    0      0
482       0    0      0
483       0    0      0
484       0    0      0
485       0    0      0
486       0    0      0
487       0    0      0
488       0    0      0
489       0    0      0
490       0    0      0
491       0    0      0
492       0    0      0
493       0    0      0
494       0    0      0
495       0    0      0
496       0    0      0
497       0    0      0
498       0    0      0
499       0    0      0

[500 rows x 3 columns]

In [181]:
for i in T:
    for j in range(P.shape[1]):
        movie_rat.loc[j, 'rating'] += cosine_sim[len(cosine_sim) - 1,i]*P[i,j]
        movie_rat.loc[j,'sim'] += cosine_sim[len(cosine_sim) - 1,i]
movie_rat['score'] = movie_rat['rating']/movie_rat['sim']

In [182]:
movie_rat

rating      sim     score
0    4.683897  2.51282  1.864000
1    5.592298  2.51282  2.225507
2    2.782467  2.51282  1.107308
3    5.989315  2.51282  2.383503
4    2.890281  2.51282  1.150214
5    1.877324  2.51282  0.747099
6    5.113352  2.51282  2.034906
7    2.891913  2.51282  1.150863
8    6.477314  2.51282  2.577707
9    5.611680  2.51282  2.233220
10   1.104848  2.51282  0.439685
11   3.675979  2.51282  1.462890
12   2.258258  2.51282  0.898695
13   3.353935  2.51282  1.334730
14   3.080883  2.51282  1.226066
15   0.938144  2.51282  0.373343
16   1.200348  2.51282  0.477689
17   3.174121  2.51282  1.263171
18   3.198683  2.51282  1.272945
19   3.568494  2.51282  1.420115
20   1.550466  2.51282  0.617022
21   3.848596  2.51282  1.531584
22   2.493823  2.51282  0.992440
23   3.210908  2.51282  1.277810
24   6.379779  2.51282  2.538892
25   2.490940  2.51282  0.991293
26   1.961698  2.51282  0.780676
27   3.174121  2.51282  1.263171
28   2.991801  2.51282  1.190615
29   5.109232  2.51282  2.033266
..        ...      ...       ...
470  0.184183  2.51282  0.073297
471  1.007285  2.51282  0.400858
472  1.436426  2.51282  0.571639
473  0.000000  2.51282  0.000000
474  0.000000  2.51282  0.000000
475  0.000000  2.51282  0.000000
476  0.000000  2.51282  0.000000
477  1.101058  2.51282  0.438176
478  0.619044  2.51282  0.246354
479  0.000000  2.51282  0.000000
480  0.000000  2.51282  0.000000
481  0.393305  2.51282  0.156519
482  0.486832  2.51282  0.193739
483  1.256620  2.51282  0.500084
484  1.495888  2.51282  0.595302
485  0.544839  2.51282  0.216824
486  1.042177  2.51282  0.414744
487  0.486832  2.51282  0.193739
488  0.000000  2.51282  0.000000
489  0.436393  2.51282  0.173667
490  1.492186  2.51282  0.593829
491  0.000000  2.51282  0.000000
492  0.581881  2.51282  0.231565
493  0.000000  2.51282  0.000000
494  0.503642  2.51282  0.200429
495  0.393305  2.51282  0.156519
496  0.000000  2.51282  0.000000
497  1.093657  2.51282  0.435231
498  0.131102  2.51282  0.052173
499  1.023236  2.51282  0.407206

[500 rows x 3 columns]

In [183]:
movie_rat = movie_rat.sort_values('score' , ascending = False)
movie_rat

rating      sim     score
8    6.477314  2.51282  2.577707
24   6.379779  2.51282  2.538892
3    5.989315  2.51282  2.383503
9    5.611680  2.51282  2.233220
1    5.592298  2.51282  2.225507
6    5.113352  2.51282  2.034906
29   5.109232  2.51282  2.033266
0    4.683897  2.51282  1.864000
60   4.273683  2.51282  1.700752
62   4.165613  2.51282  1.657744
351  4.020174  2.51282  1.599865
33   3.921254  2.51282  1.560499
21   3.848596  2.51282  1.531584
105  3.827828  2.51282  1.523320
273  3.693713  2.51282  1.469947
11   3.675979  2.51282  1.462890
168  3.573583  2.51282  1.422140
19   3.568494  2.51282  1.420115
87   3.518291  2.51282  1.400136
306  3.427362  2.51282  1.363950
51   3.418626  2.51282  1.360474
32   3.395261  2.51282  1.351175
122  3.387397  2.51282  1.348046
13   3.353935  2.51282  1.334730
68   3.258260  2.51282  1.296655
23   3.210908  2.51282  1.277810
18   3.198683  2.51282  1.272945
85   3.178637  2.51282  1.264968
27   3.174121  2.51282  1.263171
17   3.174121  2.51282  1.263171
..        ...      ...       ...
58   0.000000  2.51282  0.000000
341  0.000000  2.51282  0.000000
420  0.000000  2.51282  0.000000
44   0.000000  2.51282  0.000000
365  0.000000  2.51282  0.000000
432  0.000000  2.51282  0.000000
431  0.000000  2.51282  0.000000
288  0.000000  2.51282  0.000000
428  0.000000  2.51282  0.000000
209  0.000000  2.51282  0.000000
425  0.000000  2.51282  0.000000
252  0.000000  2.51282  0.000000
253  0.000000  2.51282  0.000000
332  0.000000  2.51282  0.000000
421  0.000000  2.51282  0.000000
255  0.000000  2.51282  0.000000
340  0.000000  2.51282  0.000000
333  0.000000  2.51282  0.000000
417  0.000000  2.51282  0.000000
334  0.000000  2.51282  0.000000
158  0.000000  2.51282  0.000000
206  0.000000  2.51282  0.000000
410  0.000000  2.51282  0.000000
205  0.000000  2.51282  0.000000
124  0.000000  2.51282  0.000000
336  0.000000  2.51282  0.000000
406  0.000000  2.51282  0.000000
285  0.000000  2.51282  0.000000
404  0.000000  2.51282  0.000000
301  0.000000  2.51282  0.000000

[500 rows x 3 columns]

In [184]:
K = movie_rat.index[:30]
# for i in T:
#     I = I.append(W.loc[W['movieId'] == i])
# I = I.reset_index(drop=True)
# I
K_ = []
for i in range(len(K)):
    if(K[i] > 14):
        K_.append(K[i])
K_ = K_[:15]
K_

[24, 29, 60, 62, 351, 33, 21, 105, 273, 168, 19, 87, 306, 51, 32]

In [185]:
# for index, row in X.iterrows():
#     #print(row['movieId'])
#     X[index,'count'] = X.loc[X['movieId'] == row['movieId']].shape[0]
#     #print(row['count'])
# X
answer = pd.DataFrame()
for i in K_:
    answer = answer.append(W.loc[W['movieId'] == i])
answer

movieId                                              title  \
24        24                        Seven (a.k.a. Se7en) (1995)   
29        29                                  Fight Club (1999)   
60        60  Lord of the Rings: The Return of the King, The...   
62        62                                     Memento (2000)   
351      351                                  Disclosure (1994)   
33        33                  Ace Ventura: Pet Detective (1994)   
21        21                          Dances with Wolves (1990)   
105      105  Dr. Strangelove or: How I Learned to Stop Worr...   
273      273                       Beverly Hills Cop III (1994)   
168      168                            Dark Knight, The (2008)   
19        19          Twelve Monkeys (a.k.a. 12 Monkeys) (1995)   
87        87  Léon: The Professional (a.k.a. The Professiona...   
306      306                                     Rob Roy (1995)   
51        51                                    Stargate (1994)   
32        32                              Lion King, The (1994)   

                                              genres  
24                                  Mystery|Thriller  
29                       Action|Crime|Drama|Thriller  
60                    Action|Adventure|Drama|Fantasy  
62                                  Mystery|Thriller  
351                                   Drama|Thriller  
33                                            Comedy  
21                           Adventure|Drama|Western  
105                                       Comedy|War  
273                     Action|Comedy|Crime|Thriller  
168                          Action|Crime|Drama|IMAX  
19                           Mystery|Sci-Fi|Thriller  
87                       Action|Crime|Drama|Thriller  
306                         Action|Drama|Romance|War  
51                           Action|Adventure|Sci-Fi  
32   Adventure|Animation|Children|Drama|Musical|IMAX

In [186]:
# X.loc[X['movieId'] == 1].shape
len(P)

998

In [187]:
# X['freq'] = X.groupby('movieId')['movieId'].transform('count')
# X = X.sort_values(['freq' , 'movieId'] , ascending = [False , True])
# X.reset_index()

In [188]:
# 

In [189]:
# sorter = X['movieId'].value_counts().index
# sorter

In [190]:
# sorterIndex = dict(zip(sorter,range(len(sorter))))

# # Generate a rank column that will be used to sort
# # the dataframe numerically
# W['movieId_Rank'] = W['movieId'].map(sorterIndex)

# # Here is the result asked with the lexicographic sort
# # Result may be hard to analyze, so a second sorting is
# # proposed next
# ## NOTE: 
# ## Newer versions of pandas use 'sort_value' instead of 'sort'
# W.sort_values(['movieId_Rank'], \
#         ascending = [True], inplace = True)
# W.drop('movieId_Rank', 1, inplace = True)


In [191]:
# W = W.reset_index()
# W.drop('index' , axis = 1)
# W.index

In [192]:
##Item - Item

In [193]:
Q = np.transpose(P)
cosine_sim_item = cosine_similarity(Q , Q)
cosine_sim_item

array([[1.        , 0.63770391, 0.74130372, ..., 0.27410794, 0.28308924,
        0.35640132],
       [0.63770391, 1.        , 0.6500004 , ..., 0.19899885, 0.24093534,
        0.26005902],
       [0.74130372, 0.6500004 , 1.        , ..., 0.28830999, 0.30030002,
        0.33728295],
       ...,
       [0.27410794, 0.19899885, 0.28830999, ..., 1.        , 0.13593597,
        0.41074392],
       [0.28308924, 0.24093534, 0.30030002, ..., 0.13593597, 1.        ,
        0.15272139],
       [0.35640132, 0.26005902, 0.33728295, ..., 0.41074392, 0.15272139,
        1.        ]])

In [194]:
cosine_sim_item[:15]

array([[1.        , 0.63770391, 0.74130372, ..., 0.27410794, 0.28308924,
        0.35640132],
       [0.63770391, 1.        , 0.6500004 , ..., 0.19899885, 0.24093534,
        0.26005902],
       [0.74130372, 0.6500004 , 1.        , ..., 0.28830999, 0.30030002,
        0.33728295],
       ...,
       [0.48020234, 0.53797994, 0.48144301, ..., 0.16329717, 0.25888866,
        0.21192243],
       [0.55497082, 0.61761085, 0.55620287, ..., 0.19382693, 0.25573   ,
        0.19750477],
       [0.68148936, 0.49549516, 0.61495857, ..., 0.25930013, 0.29567923,
        0.34405497]])

In [195]:
for i in range(n):
    for j in range(n):
         cosine_sim_item[i,j] = 0
cosine_sim_item

array([[0.        , 0.        , 0.        , ..., 0.27410794, 0.28308924,
        0.35640132],
       [0.        , 0.        , 0.        , ..., 0.19899885, 0.24093534,
        0.26005902],
       [0.        , 0.        , 0.        , ..., 0.28830999, 0.30030002,
        0.33728295],
       ...,
       [0.27410794, 0.19899885, 0.28830999, ..., 1.        , 0.13593597,
        0.41074392],
       [0.28308924, 0.24093534, 0.30030002, ..., 0.13593597, 1.        ,
        0.15272139],
       [0.35640132, 0.26005902, 0.33728295, ..., 0.41074392, 0.15272139,
        1.        ]])

In [196]:
Q

array([[4. , 0. , 0. , ..., 0. , 5. , 4. ],
       [0. , 0. , 0. , ..., 0. , 3. , 1. ],
       [3.5, 0. , 5. , ..., 0. , 1. , 3. ],
       ...,
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 0. , ..., 0. , 0. , 0. ],
       [0. , 0. , 3. , ..., 0. , 0. , 0. ]])

In [197]:
L = []
for i in range(n):
    L.append(cosine_sim_item[i].argsort()[-15:][::-1])

In [198]:
L

[array([ 24,  83,  18,  22,  19,  17,  29,  23,  21,  62, 108,  28,  20,
         25,  86]),
 array([39, 25, 41, 32, 23, 37, 24, 17, 21, 27, 70, 66, 72, 33, 26]),
 array([ 24,  22,  17,  21,  23,  18,  25,  19,  42, 108,  20,  83,  28,
         35,  30]),
 array([24, 21, 25, 20, 28, 17, 29, 23, 32, 73, 41, 35, 19, 18, 30]),
 array([25, 23, 17, 41, 32, 37, 51, 39, 27, 38, 21, 24, 66, 45, 33]),
 array([16, 15, 20, 56, 26, 63, 42, 47, 59, 28, 76, 36, 55, 61, 48]),
 array([21, 25, 23, 17, 24, 38, 42, 69, 57, 37, 20, 35, 51, 85, 64]),
 array([25, 42, 23, 51, 17, 38, 37, 24, 19, 57, 39, 76, 15, 36, 64]),
 array([29, 30, 34, 43, 16, 44, 20, 18, 26, 67, 36, 35, 60, 62, 63]),
 array([21, 25, 35, 41, 18, 24, 39, 22, 32, 28, 17, 20, 19, 73, 66]),
 array([ 23,  25,  17,  69,  21,  88,  85, 120,  38, 185,  49,  51,  41,
         27,  32]),
 array([126,  26,  52,  15,  71,  20,  19,  36,  31,  27,  42,  16,  58,
         32,  54]),
 array([ 31,  45,  58,  25,  19,  15,  36,  23, 171, 135, 172,  26, 

In [199]:
movie_rat_1 = pd.DataFrame(columns=['rating','count','score'] , index=range(0,500))
movie_rat_1['rating'] = 0
movie_rat_1['count'] = 0
movie_rat_1['score'] = 0
movie_rat_1
for index,row in movie_rat_1.iterrows():
    p = X.loc[X['movieId'] == index].shape[0]
    q = X.loc[X['movieId'] == index].rating.sum()
    movie_rat_1.set_value(index , 'rating' , q)
    movie_rat_1.set_value(index , 'count' , p)   
movie_rat_1['score'] = movie_rat_1['rating']/movie_rat_1['count']
movie_rat_1

/home/sarvagya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':
/home/sarvagya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  # Remove the CWD from sys.path while we load stuff.


rating  count     score
0      2064    498  4.144578
1      1969    488  4.034836
2      1847    446  4.141256
3      1963    442  4.441176
4      1581    443  3.568849
5      1575    379  4.155673
6      1532    387  3.958656
7      1439    368  3.910326
8      1552    382  4.062827
9      1647    395  4.169620
10     1353    336  4.026786
11     1388    346  4.011561
12     1180    356  3.314607
13     1342    346  3.878613
14     1591    375  4.242667
15     1386    363  3.818182
16     1371    333  4.117117
17     1095    323  3.390093
18     1512    373  4.053619
19     1213    315  3.850794
20     1460    364  4.010989
21     1160    313  3.706070
22     1323    329  4.021277
23     1185    344  3.444767
24     1496    380  3.936842
25     1072    297  3.609428
26     1233    317  3.889590
27     1105    305  3.622951
28     1353    313  4.322684
29     1537    368  4.176630
..      ...    ...       ...
470     255     80  3.187500
471     259     71  3.647887
472     240     98  2.448980
473     285     82  3.475610
474     252     65  3.876923
475     246     80  3.075000
476     234     70  3.342857
477     398    106  3.754717
478     283     74  3.824324
479     271     87  3.114943
480     195     61  3.196721
481     377    112  3.366071
482     295     87  3.390805
483     305     79  3.860759
484     329     81  4.061728
485     286     78  3.666667
486     278     83  3.349398
487     349     89  3.921348
488     216     69  3.130435
489     320     95  3.368421
490     280     86  3.255814
491     365    101  3.613861
492     342     88  3.886364
493     348    103  3.378641
494     318     81  3.925926
495     180     72  2.500000
496     289     75  3.853333
497     244     57  4.280702
498     242     72  3.361111
499     296     76  3.894737

[500 rows x 3 columns]

In [200]:
# for i in L:
#     for j in range(len(i)):
#         i[j] = i[j] * movie_rat_1.loc[j , 'score']
L

[array([ 24,  83,  18,  22,  19,  17,  29,  23,  21,  62, 108,  28,  20,
         25,  86]),
 array([39, 25, 41, 32, 23, 37, 24, 17, 21, 27, 70, 66, 72, 33, 26]),
 array([ 24,  22,  17,  21,  23,  18,  25,  19,  42, 108,  20,  83,  28,
         35,  30]),
 array([24, 21, 25, 20, 28, 17, 29, 23, 32, 73, 41, 35, 19, 18, 30]),
 array([25, 23, 17, 41, 32, 37, 51, 39, 27, 38, 21, 24, 66, 45, 33]),
 array([16, 15, 20, 56, 26, 63, 42, 47, 59, 28, 76, 36, 55, 61, 48]),
 array([21, 25, 23, 17, 24, 38, 42, 69, 57, 37, 20, 35, 51, 85, 64]),
 array([25, 42, 23, 51, 17, 38, 37, 24, 19, 57, 39, 76, 15, 36, 64]),
 array([29, 30, 34, 43, 16, 44, 20, 18, 26, 67, 36, 35, 60, 62, 63]),
 array([21, 25, 35, 41, 18, 24, 39, 22, 32, 28, 17, 20, 19, 73, 66]),
 array([ 23,  25,  17,  69,  21,  88,  85, 120,  38, 185,  49,  51,  41,
         27,  32]),
 array([126,  26,  52,  15,  71,  20,  19,  36,  31,  27,  42,  16,  58,
         32,  54]),
 array([ 31,  45,  58,  25,  19,  15,  36,  23, 171, 135, 172,  26, 

In [201]:
movie_rat_2 = pd.DataFrame(columns=['rating','count','score'] , index=range(0,500))
movie_rat_2['rating'] = 0
movie_rat_2['count'] = 0
movie_rat_2['score'] = 0
movie_rat_2

rating  count  score
0         0      0      0
1         0      0      0
2         0      0      0
3         0      0      0
4         0      0      0
5         0      0      0
6         0      0      0
7         0      0      0
8         0      0      0
9         0      0      0
10        0      0      0
11        0      0      0
12        0      0      0
13        0      0      0
14        0      0      0
15        0      0      0
16        0      0      0
17        0      0      0
18        0      0      0
19        0      0      0
20        0      0      0
21        0      0      0
22        0      0      0
23        0      0      0
24        0      0      0
25        0      0      0
26        0      0      0
27        0      0      0
28        0      0      0
29        0      0      0
..      ...    ...    ...
470       0      0      0
471       0      0      0
472       0      0      0
473       0      0      0
474       0      0      0
475       0      0      0
476       0      0      0
477       0      0      0
478       0      0      0
479       0      0      0
480       0      0      0
481       0      0      0
482       0      0      0
483       0      0      0
484       0      0      0
485       0      0      0
486       0      0      0
487       0      0      0
488       0      0      0
489       0      0      0
490       0      0      0
491       0      0      0
492       0      0      0
493       0      0      0
494       0      0      0
495       0      0      0
496       0      0      0
497       0      0      0
498       0      0      0
499       0      0      0

[500 rows x 3 columns]

In [202]:
for i in L:
    for j in range(len(i)):
        movie_rat_2.loc[i[j],'rating'] += movie_rat_1.loc[j , 'score']
        movie_rat_2.loc[i[j],'count'] += 1
movie_rat_2['score'] = movie_rat_2['rating']/movie_rat_2['count']
movie_rat_2 = movie_rat_2.sort_values('score' , ascending = False)
movie_rat_2

rating  count     score
43    4.441176      1  4.441176
84    4.441176      1  4.441176
56    4.441176      1  4.441176
48    4.242667      1  4.242667
54    4.242667      1  4.242667
103   4.242667      1  4.242667
64    8.485333      2  4.242667
67    8.412287      2  4.206143
86    8.398339      2  4.199170
63    8.398339      2  4.199170
69   12.521123      3  4.173708
30   12.520169      3  4.173390
135   4.169620      1  4.169620
185   4.169620      1  4.169620
88    4.155673      1  4.155673
44    4.155673      1  4.155673
126   4.144578      1  4.144578
34    4.141256      1  4.141256
52    4.141256      1  4.141256
38   20.606620      5  4.121324
57    8.232447      2  4.116224
37   16.439622      4  4.109906
22   16.421175      4  4.105294
31    8.207406      2  4.103703
108   8.196406      2  4.098203
85   12.278446      3  4.092815
25   45.003875     11  4.091261
120   8.152993      2  4.076496
17   40.717086     10  4.071709
21   36.631036      9  4.070115
..         ...    ...       ...
470   0.000000      0       NaN
471   0.000000      0       NaN
472   0.000000      0       NaN
473   0.000000      0       NaN
474   0.000000      0       NaN
475   0.000000      0       NaN
476   0.000000      0       NaN
477   0.000000      0       NaN
478   0.000000      0       NaN
479   0.000000      0       NaN
480   0.000000      0       NaN
481   0.000000      0       NaN
482   0.000000      0       NaN
483   0.000000      0       NaN
484   0.000000      0       NaN
485   0.000000      0       NaN
486   0.000000      0       NaN
487   0.000000      0       NaN
488   0.000000      0       NaN
489   0.000000      0       NaN
490   0.000000      0       NaN
491   0.000000      0       NaN
492   0.000000      0       NaN
493   0.000000      0       NaN
494   0.000000      0       NaN
495   0.000000      0       NaN
496   0.000000      0       NaN
497   0.000000      0       NaN
498   0.000000      0       NaN
499   0.000000      0       NaN

[500 rows x 3 columns]

In [203]:
ans = movie_rat_2.index[:15]
ans

Int64Index([43, 84, 56, 48, 54, 103, 64, 67, 86, 63, 69, 30, 135, 185, 88], dtype='int64')

In [204]:
answer = pd.DataFrame()
for i in ans:
    answer = answer.append(W.loc[W['movieId'] == i])
answer

movieId                                             title  \
43        43     Lord of the Rings: The Two Towers, The (2002)   
84        84                          L.A. Confidential (1997)   
56        56         Indiana Jones and the Last Crusade (1989)   
48        48                        Princess Bride, The (1987)   
54        54                              Groundhog Day (1993)   
103      103                             Ocean's Eleven (2001)   
64        64                                  GoldenEye (1995)   
67        67                         Fifth Element, The (1997)   
86        86                                 Goodfellas (1990)   
63        63  Star Wars: Episode I - The Phantom Menace (1999)   
69        69                   Clear and Present Danger (1994)   
30        30                           Sixth Sense, The (1999)   
135      135                                 Armageddon (1998)   
185      185                        In the Line of Fire (1993)   
88        88                                  Firm, The (1993)   

                                      genres  
43                         Adventure|Fantasy  
84          Crime|Film-Noir|Mystery|Thriller  
56                          Action|Adventure  
48   Action|Adventure|Comedy|Fantasy|Romance  
54                    Comedy|Fantasy|Romance  
103                           Crime|Thriller  
64                 Action|Adventure|Thriller  
67            Action|Adventure|Comedy|Sci-Fi  
86                               Crime|Drama  
63                   Action|Adventure|Sci-Fi  
69               Action|Crime|Drama|Thriller  
30                      Drama|Horror|Mystery  
135           Action|Romance|Sci-Fi|Thriller  
185                          Action|Thriller  
88                            Drama|Thriller